name: clean root images
on: workflow_dispatch
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -f *.jpg *.png
          rm -f *.jpeg
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add -A
          git commit -m "clean root images" || exit 0
          git push
