name: clean root images
on: workflow_dispatch
permissions:
  contents: write
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf .GitHub
          rm -f *.gif *.jpg *.png *.jpeg
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add -A
          git commit -m "clean gifs and capital GitHub" || exit 0
          git push
